apiVersion: v1
kind: Pod
metadata:
  name: docker-ssh
  labels:
    environment: production
    app: docker-ssh
spec:
  containers:
  - name: docker-ssh
    image: irom77/docker-ssh:latest
    ports:
        - containerPort: 2222    
    env: 
    - name: SSH_MASTER_USER
      value: azureuser
    - name: SSH_MASTER_PASS
      valueFrom:
        secretKeyRef:
          name: pan-python
          key: azureuser_pass 
    volumeMounts:
    - name: azurefileshare
      mountPath: /mnt/azure 
    imagePullPolicy: IfNotPresent             
  volumes:
  - name: azurefileshare
    azureFile:
      secretName: azure-secret
      shareName: aksshare
      readOnly: false  
---
apiVersion: v1
kind: Service
metadata:
  name: docker-ssh
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 22
  selector:
    app: docker-ssh         